### ISSUE TITLE
Refactor requires() helper

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-test-helpers#110]
`try/catch` at https://github.com/softlayer/sl-ember-test-helpers/blob/master/test-support/helpers/sl/synchronous/requires.js#L82-L87 needs to be replaced with `assert.throws()` call.  https://github.com/softlayer/sl-ember-components/blob/develop/tests/unit/components/sl-chart-test.js#L99 can be referenced as an example implementation.

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by erangeles** [comment]
@notmessenger So I've tested a few different methods on implementing this, however I think it's not possible to actually use "assert.throws" in this helper. Because we are returning an object with an aggregation of results for these tests and the only way we can actually capture these errors is using a try catch block. Would like your input :smiley:

**Comment by notmessenger** [comment]
@erangeles Upon review, I would agree with your assessment.  Am closing this issue.
